# Etapa de construcción con Maven
FROM maven:3.8.4-jdk-11 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -P war

# Etapa de ejecución
FROM tomcat:9.0.65-jdk11-openjdk-slim
COPY --from=builder /app/target/ROOT.war /usr/local/tomcat/webapps/
CMD ["catalina.sh", "run"]
