version: '3.1'

services:
  MariaDB:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: test123   # Nuevo usuario
      MYSQL_PASSWORD: 123adminmaria   # Contraseña del nuevo usuario
      # MYSQL_DATABASE: testdb   # Nombre de la nueva base de datos


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: MariaDB
      PMA_ARBITRARY: 1
